spring.application.name=recipe-api

# let Spring Boot start the embedded web server
# (omit or set to servlet; don't set to NONE)
# spring.main.web-application-type=servlet

# HTTP port
server.port=8081

# PostgreSQL connection
spring.datasource.url=jdbc:postgresql://localhost:5432/recipe_db
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

# Let Hibernate auto-create/update for now
spring.jpa.hibernate.ddl-auto=update
